function buildSearchList (data) {
	console.log ("build search list")

	$.each(data.hotels, function(i, obj){
		$(".hotel-list").append(
              "<div class='results-card'>" 
              + "<div class='photo' style='background: url(" + obj.images + "); no-repeat; background-size: cover;'>" 
                + "<div class='count'>1 / 17</div>"
                + "<div class='save'><img src='img/heart.svg' /></div>" 
                + "<div class='prev'><img src='img/chevron-left.svg' /></div>"
                + "<div class='next'><img src='img/chevron-right.svg' /></div>"
              + "</div>"
              + "<div class='content'>"
                + "<div class='name'>" + obj.name + "</div>"
                + "<div class='rating'>"
                  + "<div class='star'>" + obj.starRating + "</div>" 
                  + "<img src='img/ta.png' class='ta'/><span class='reviews'>" + obj.ta.taReviewsNum + " reviews</span>"
                + "</div>"
                + "<div class='detail' style='margin-top:8px;'>"
                  + "<img src='img/map.svg' class='icon' />"
                  + "<span class='inline'>" + obj.destination.resort + " " + obj.destination.region + " " + obj.destination.country +"<br/> <a href='#'' class='map-link'>View on map</a></span>"
                + "</div>"
                + "<div class='detail' style='margin-top:8px;'>"
                  + "<img src='img/cal.svg' class='icon' />"
                  + "<span class='inline' style='font-size:14px;'>" + obj.dateRange + "</span>"
                + "</div>"
                + "<div class='detail'>"
                  + "<img src='img/flight.svg' class='icon' />" 
                  + "<span class='inline'><a href='#'' class='inline-link'>" + obj.flight.direct + " from " + obj.flight.departureAirport + "</a></span>"
                + "</div>"
                + "<div class='detail'>"
                  + "<img src='img/board.svg' class='icon' />"
                  + "<span class='inline'>" + obj.boardBasis + "</span>"
                + "</div>"
                + "<div class='detail'>"
                  + "<img src='img/bags.svg' class='icon' />"
                  + "<span class='inline'><a href='#'' class='inline-link'>Hold bags:" + obj.flight.holdBags + "</a></span>"
                + "</div>" 
              + "</div>"
              + "<div class='action'>" 
                + "<div class='price'>"
                  + "<div class='from'>Prices from</div>"
                  + "<div class='price-lead'>£" + obj.price.pricePerPerson + "<span>pp</span></div>"
                  + "<div class='price-secondary'>£" + obj.price.totalPrice + " Total Price</div>"
                + "</div>"
                + "<div class='cta'>"
                  + "<div class='button'>More details</div>"
                + "</div>"
              + "</div>"
              + "</div>"
            );
	})
}